# Generated by Django 4.2.3 on 2023-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_budget_current_limit_alter_coupons_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
